service: c-sharp-lambda-demo
provider:
  name: aws
  runtime: dotnetcore3.1
  logRetentionInDays: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt [stateManager, Arn]

functions:
  teh_func:
    environment:
      STATE_TBL_NAME: !Ref stateManager
    handler: lambda::AwsDotnetCsharp.Handler::Hello
    package:
      individually: true
      artifact: lambda/bin/Debug/netcoreapp3.1/csharpfunction.zip
resources:
  Resources:
    stateManager:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-state
        AttributeDefinitions:
          - AttributeName: resourceId
            AttributeType: S
        KeySchema:
          - AttributeName: resourceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  Outputs:
    StateManagerArn:
      Value: !GetAtt [stateManager, Arn]
    StateManagerName:
      Value: !Ref stateManager
